### ISSUE TITLE
Netlify build error on demo starter

### ISSUE THREAD

**Issue by arwinstratingws** [uniformdev/uniform-optimize-next-sanity-starter#1]
Hello,

Today i stumbled upon the Uniform project and became instantly interested in it. I therefore tried to setup a demo by following the accompanied steps. 

I configured a project with the combination of Next.js, Sanity and Netlify. This resulted in cloning this repository in my personal Github space. While building the repo from Netlify I received the following error:

```
12:42:13 PM: Error occurred prerendering page "/registration". Read more: https://nextjs.org/docs/messages/prerender-error
12:42:13 PM: TypeError: Cannot read properties of null (reading 'components')
12:42:13 PM:     at getPageBySlug (/opt/build/repo/.next/server/pages/[[...slug]].js:688:30)
12:42:13 PM:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
12:42:13 PM:     at async getStaticProps (/opt/build/repo/.next/server/pages/[[...slug]].js:717:13)
12:42:13 PM:     at async renderToHTML (/opt/build/repo/node_modules/next/dist/server/render.js:329:24)
12:42:13 PM:     at async /opt/build/repo/node_modules/next/dist/export/worker.js:273:36
12:42:13 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:60:20)
```

This error occured for all available pages:

```
12:42:14 PM: Error: Export encountered errors on following paths:
12:42:14 PM: 	/
12:42:14 PM: 	/developers
12:42:14 PM: 	/marketers
12:42:14 PM: 	/registration
12:42:14 PM:     at /opt/build/repo/node_modules/next/dist/export/index.js:487:19
12:42:14 PM:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
12:42:14 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:60:20)
12:42:14 PM:     at async /opt/build/repo/node_modules/next/dist/build/index.js:833:17
12:42:14 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:60:20)
12:42:14 PM:     at async /opt/build/repo/node_modules/next/dist/build/index.js:707:13
12:42:14 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:60:20)
12:42:14 PM:     at async Object.build [as default] (/opt/build/repo/node_modules/next/dist/build/index.js:77:25)
```

Is there any way to fix this?

Thanks in advance!

**Comment by arwinstratingws** [comment]
Hey @alexshyba thanks for looking into my issue!

I will retry creating the demo environment and hope this will fix things. If i have further questions i'll make sure to head into the discord :) 

Thanks again!
